version: 4.0.0-beta-{build}
clone_depth: 3
clone_folder: c:\work\sharp-arch
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
os: Visual Studio 2015
install:
- cmd: git submodule update --init --recursive
build:
  project: Build\build.proj
  parallel: true
  verbosity: normal
before_build:
- cmd: nuget restore Solutions/SharpArch.sln
build_script:
  - cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" Build\Build.proj /t:Build,Package,FindDuplicates,InspectCode,PackageNuget'
artifacts:
- path: Drops/**/*.nupkg
  name: Nugets
- path: Drops/**/*.zip
  name: Binaries 
- path: Drops/Duplicates/CodeDuplicatesReport.html
  name: CodeDuplicates
- path: Drops/Inspections/CodeInspectionsReport.html
  name: CodeInspections
test_script:
- cmd: >-
    cd Solutions\SharpArch.Tests\bin\Release

    nunit3-console SharpArch.Tests.dll --result=myresults.xml;format=AppVeyor --dispose-runners --nocolor

    cd ..\..\..\SharpArch.Specifications\bin\Release

    mspec-clr4.exe SharpArch.Specifications.dll
deploy:
- provider: NuGet
  api_key:
    secure: QzSLSnRAnpTRqWWhDzHNkHJP6RCd5pwWMv0myf88h0OCk0TTPJdhflsDql3kAlip
  on:
    branch: master
